export function enforceLimits(test, cfg) {
  const rps = Number(test.targetRps),
    duration = Number(test.totalDurationSeconds);
  if (!Number.isFinite(rps) || rps < 1)
    throw new Error("Target RPS must be positive");
  if (rps > 1000 && !cfg.allowHighLoad)
    throw new Error("RPS above 1,000 requires ALLOW_HIGH_LOAD=true");
  if (rps > cfg.maxAllowedRps)
    throw new Error(`RPS exceeds configured maximum ${cfg.maxAllowedRps}`);
  const distributedThreshold = cfg.distributedRequiredThreshold ?? 1_000_000;
  if (rps >= distributedThreshold && !cfg.distributedProvider)
    throw new Error(
      `${rps.toLocaleString()} RPS cannot be generated by a single machine. Distributed planning mode only: ` +
        "configure an approved provider, sufficient network capacity, and written authorization first.",
    );
  const confirmationThreshold = cfg.highLoadConfirmationThreshold ?? 10_000;
  if (
    rps > confirmationThreshold &&
    (test.confirmDomain !== test.hostname || Number(test.confirmRps) !== rps)
  )
    throw new Error("High-load confirmation must exactly match domain and RPS");
  if (!Number.isFinite(duration) || duration < 1 || duration > cfg.maxDuration)
    throw new Error("Test duration exceeds configured maximum");
  return true;
}
export function emergencyStop(sample, limits) {
  const reasons = [];
  if (sample.errorRate > limits.maxErrorRate) reasons.push("error-rate");
  if (sample.p95 > limits.maxP95Ms) reasons.push("p95-latency");
  if (sample.badStatusRate > limits.maxBadStatusRate)
    reasons.push("upstream-status");
  if (sample.unavailable) reasons.push("target-unavailable");
  if (sample.elapsedSeconds >= limits.maxDuration)
    reasons.push("maximum-duration");
  return { stop: reasons.length > 0, reasons };
}
