export const cfg = {
  allowedTargets: [
    "idiccambodia.com",
    "idic.edu.kh",
    "api.idiccambodia.com",
    "production-api.idiccambodia.com",
  ],
  verifiedTargets: ["idiccambodia.com"],
  allowedIpTargets: [],
  allowPrivateTargets: false,
  allowHighLoad: false,
  maxAllowedRps: 1000,
  maxDuration: 3600,
  distributedProvider: "",
};
export const sample = {
  name: "smoke",
  preset: "smoke",
  method: "GET",
  baseUrl: "https://idiccambodia.com",
  endpoint: "/healthz",
  query: {},
  headers: {},
  auth: { type: "none" },
  targetRps: 10,
  startingRps: 10,
  rampUpSeconds: 0,
  steadySeconds: 30,
  rampDownSeconds: 0,
  requestTimeoutMs: 5000,
  maxVus: 100,
  expectedStatus: 200,
  thinkTimeMs: 0,
  instances: 1,
  stopThresholds: {
    maxErrorRate: 0.05,
    maxP95Ms: 1000,
    maxBadStatusRate: 0.05,
  },
  totalDurationSeconds: 30,
  hostname: "idiccambodia.com",
};
